### ISSUE TITLE
Changes the launcher icon back to android default

### ISSUE THREAD

**Issue by Mandrakia** [BoardiesITSolutions/FileDirectoryPicker#1]
When adding the library to the project and launching my app, my launcher icon reverted back to default android launcher icon.

**Comment by boardy** [comment]
Hi Mandrakia, 

Sorry about that, I changed my launcher icon name so hadn't noticed this happened. It it fixed now and a new release has been made available. If you reference the tagged version 1.0.0.6 it should be OK now.

Thanks

Chris

**Comment by Mandrakia** [comment]
Thanks for the quick response !
