### ISSUE TITLE
Failed resolution of: Lcom/BoardiesITSolutions/FileDirectoryPicker/BasePicker

### ISSUE THREAD

**Issue by MooonWalker** [BoardiesITSolutions/FileDirectoryPicker#4]
In my button click listener i am receiving the error message:
"Failed resolution of: Lcom/BoardiesITSolutions/FileDirectoryPicker/BasePicker"

What is missing for me?

**Comment by MooonWalker** [comment]
latest tag is with AndroidX which is not implemented in my app. Reverted back to 1.0.0.6

**Comment by boardy** [comment]
Glad you got resolved. I would recommend upgrading to AndroidX if possible though as it replaced the Android Support Library quite some time ago and don't believe it is any longer maintained.
